version: '3'

services:
  db:
    image: postgres
  web:
    image: vagnerrguedess/dj
    command: ./wait-for-it.sh db:5432 -- python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:Z
    ports:
      - "8000:8000"
    depends_on:
      - db
